<?php

namespace App\Class;

class QuartetSettings 
{
    const CATEGORIES_AND_LABELS = [
        'zalm'          => 'Zalm',
        'rood'          => 'Rood',
        'roze'          => 'Roze',
        'geel'          => 'Geel',
        'goud'          => 'Goud',
        'cyaan'         => 'Cyaan',
        'turkoois'      => 'Turkoois',
        'blauw'         => 'Blauw',
        'oranje'        => 'Oranje',
        'groengeel'     => 'Groengeel',
        'limoen'        => 'Limoen',
        'groen'         => 'Groen',
        'lavendel'      => 'Lavendel',
        'fuchsia'       => 'Fuchisa',
        'wit'           => 'Wit',
        'zwart'         => 'Zwart',
        'bruin'         => 'Bruin',
        'nachtblauw'    => 'Nachtblauw',
        'donkerrood'    => 'Donkerrood',
        'lichtgeel'     => 'Lichtgeel',
        'lichtcyaan'    => 'lichtcyaan',
        'hemelsblauw'   => 'Hemelsblauw',
        'lichtzalm'     => 'Lichtzalm',
        'koraal'        => 'Koraal',
        'tomaat'        => 'Tomaat',
        'pruim'         => 'Pruim',
        'violet'        => 'Violet',
        'orchidee'      => 'Orchidee',
        'paars'         => 'Paarts',
        'indigo'        => 'Indigo',
    ];

    const CATEGORIES_AND_COLORS = [
        'zalm'          => '#E9967A',
        'rood'          => '#FF0000',
        'roze'          => '#FF00CB',
        'geel'          => '#FFFF00',
        'goud'          => '#FFD700',
        'cyaan'         => '#00FFFF',
        'turkoois'      => '#40E0D0',
        'blauw'         => '#0000FF',
        'oranje'        => '#FFA500',
        'groengeel'     => '#ADFF00',
        'limoen'        => '#00FF00',
        'groen'         => '#008000',
        'lavendel'      => '#E6E6FA',
        'fuchsia'       => '#FF00FF',
        'wit'           => '#FFFFFF',
        'zwart'         => '#000000',
        'bruin'         => '#A52A2A',
        'nachtblauw'    => '#191970',
        'donkerrood'    => '#8B0000',
        'lichtgeel'     => '#FFFFE0',
        'lichtcyaan'    => '#E0FFFF',
        'hemelsblauw'   => '#87CEEB',
        'lichtzalm'     => '#FFA07A',
        'koraal'        => '#FF7F50',
        'tomaat'        => '#FF4500',
        'pruim'         => '#DDA0DD',
        'violet'        => '#EE82EE',
        'orchidee'      => '#DA70D6',
        'paars'         => '#800080',
        'indigo'        => '#4B0082',
    ];
}
